### ISSUE TITLE
Just wana check what are your thought on giving this Project to Apache Incubator

### ISSUE THREAD

**Issue by surapuramakhil** [killbill/killbill#1965] opened 2024-02-05 12:32 UTC
Just to Note: I am not a member of Apache.

I have found your work - solving real problem of low Revenue Business where even minor cut causes significant difference. I also notice you guys are working on this project since 2014 i.e A Decade on this project.

@sbrossie @pierre 

Reason why I asked is They Have resources (think them more as a Open Source Accelerator)

**Comment by surapuramakhil** [comment] 2024-02-06 13:20
Have you checked https://opencollective.com/ ?

**Comment by reshmabidikar** [comment] 2024-05-01 07:24
Thank you for the suggestions. Since this is not a bug in Kill Bill, I'm closing this ticket. Feel free to reach out via the [mailing list](https://groups.google.com/forum/#!forum/killbilling-users).

**Closed by reshmabidikar** 2024-05-01 07:24 UTC
