### ISSUE TITLE
Allow multiple plans with same billing period but different durations

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#271] opened 2015-02-09 15:17 UTC
The PriceList API needs to be revisited: https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/catalog/api/PriceList.java#L25

One use case is to have multiple fixed term plans with different durations:

```
   <plans>
        <plan name="cat_compact_plan_1">
            <product>cat_compact_1</product>
            <finalPhase type="FIXEDTERM">
                <duration>
                    <unit>DAYS</unit>
                    <number>1</number>
                </duration>
                <fixed>
                    <fixedPrice>
                        <price>
                            <currency>USD</currency>
                            <value>100.00</value>
                        </price>
                    </fixedPrice>
                </fixed>
            </finalPhase>
        </plan>

        <plan name="cat_compact_plan_2">
            <product>cat_compact_1</product>
            <finalPhase type="FIXEDTERM">
                <duration>
                    <unit>DAYS</unit>
                    <number>2</number>
                </duration>
                <fixed>
                    <fixedPrice>
                        <price>
                            <currency>USD</currency>
                            <value>175.00</value>
                        </price>
                    </fixedPrice>
                </fixed>
            </finalPhase>
        </plan>
   </plans>
```

Discussion: https://groups.google.com/forum/#!msg/killbilling-users/zzRVBJ9MY2o/u0STkw6xpBcJ

**Comment by sbrossie** [comment] 2015-04-10 00:23
Duplicate of #303

**Closed by sbrossie** 2015-04-10 00:23 UTC
Labels: CATALOG, enhancement
