### ISSUE TITLE
Investigate TestCatalogRetireElements failures

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#486] opened 2016-02-05 21:20 UTC
Seen locally several times:

```
[bus_events-th] INFO org.killbill.billing.invoice.notification.DefaultNextBillingDatePoster - Queuing next billing date notification at 2016-04-01T00:00:00.000Z for subscriptionId 1c044241-4844-41f8-9247-ac12a995ce0a
[notifications-th] ERROR org.killbill.billing.invoice.InvoiceDispatcher - Failed to process invoice for account 5eace2d2-3423-4ac1-bccf-32f8c79f5fe3, targetDate 2016-03-01T00:00:00.000Z
org.killbill.commons.locker.LockFailedException
	at org.killbill.commons.locker.memory.MemoryGlobalLocker.lockWithNumberOfTries(MemoryGlobalLocker.java:42)
	at org.killbill.billing.invoice.InvoiceDispatcher.processAccount(InvoiceDispatcher.java:211)
	at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionInternal(InvoiceDispatcher.java:199)
	at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionForInvoiceGeneration(InvoiceDispatcher.java:174)
	at org.killbill.billing.invoice.InvoiceListener.handleNextBillingDateEvent(InvoiceListener.java:130)
	at org.killbill.billing.invoice.notification.DefaultNextBillingDateNotifier.processEventForInvoiceGeneration(DefaultNextBillingDateNotifier.java:123)
	at org.killbill.billing.invoice.notification.DefaultNextBillingDateNotifier.access$400(DefaultNextBillingDateNotifier.java:40)
	at org.killbill.billing.invoice.notification.DefaultNextBillingDateNotifier$1.handleReadyNotification(DefaultNextBillingDateNotifier.java:93)
	at org.killbill.notificationq.NotificationQueueDispatcher.handleNotificationWithMetrics(NotificationQueueDispatcher.java:203)
	at org.killbill.notificationq.dispatching.NotificationCallableCallback.dispatch(NotificationCallableCallback.java:51)
	at org.killbill.notificationq.dispatching.NotificationCallableCallback.dispatch(NotificationCallableCallback.java:32)
	at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:102)
	at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:85)
	at org.killbill.commons.concurrent.WrappedCallable.call(WrappedCallable.java:42)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at org.killbill.commons.concurrent.WrappedRunnable.run(WrappedRunnable.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[bus_events-th] INFO org.killbill.billing.api.TestApiListener - Got Invoice event DefaultInvoiceCreationNotification [invoiceId=74baba45-ffec-4e41-bd53-fcc2b7e52ba3, accountId=5eace2d2-3423-4ac1-bccf-32f8c79f5fe3, amountOwed=49.95, currency=USD]
[bus_events-th] INFO org.killbill.billing.payment.bus.PaymentBusEventHandler - Received invoice creation notification for account 5eace2d2-3423-4ac1-bccf-32f8c79f5fe3 and invoice 74baba45-ffec-4e41-bd53-fcc2b7e52ba3
[bus_events-th] INFO org.killbill.billing.api.TestApiListener - Got PaymentInfo event class org.killbill.billing.payment.api.DefaultPaymentInfoEvent {accountId=5eace2d2-3423-4ac1-bccf-32f8c79f5fe3, paymentId=80f6eb5b-0e8e-407a-a5b7-2a2b59b2d26f, paymentTransactionId=62408b8d-a69e-4ba7-81fc-7359ec77686c, amount=49.95, currency=USD, status=SUCCESS, transactionType=PURCHASE, effectiveDate=2016-03-01T00:00:02.000Z}
[bus_events-th] INFO org.killbill.billing.api.TestApiListener - Got InvoicePaymentInfo event class org.killbill.billing.invoice.api.DefaultInvoicePaymentInfoEvent {accountId=5eace2d2-3423-4ac1-bccf-32f8c79f5fe3, paymentId=80f6eb5b-0e8e-407a-a5b7-2a2b59b2d26f, type=ATTEMPT, invoiceId=74baba45-ffec-4e41-bd53-fcc2b7e52ba3, paymentDate=2016-03-01T00:00:02.000Z, amount=49.950000000, currency=USD, linkedInvoicePaymentId=null, paymentCookieId='null', processedCurrency=USD}
[main] ERROR org.killbill.billing.api.TestApiListener - TestApiListener did not complete in 25000 ms, remaining events are NULL_INVOICE
[main] ERROR org.killbill.billing.api.TestApiListener - TestApiListener did not complete in 25000 ms, remaining events are NULL_INVOICE
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.beatrix.integration.TestCatalogRetireElements:testRetirePriceList !!! FAILURE !!! (27 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
```

**Comment by sbrossie** [comment] 2016-04-19 22:20
Tried to run them a few times, but can't seem to trigger the issue. Can this be re-produced on your side while simply running that test (or does that require running all beatrix tests)?

**Comment by pierre** [comment] 2016-04-19 22:34
IIRC, it was triggered when running the full suite 😢

**Comment by sbrossie** [comment] 2016-04-28 22:58
By looking at Travis failures, i am seeing failures in all kind of tests, so it does not seem necessary to keep bugs for each test failures. Problem seems more systemic.

Close as duplicate of #485.

**Closed by sbrossie** 2016-04-28 22:58 UTC
Labels: TEST
