### ISSUE TITLE
Add support for auto retry api payments.

### ISSUE THREAD

**Issue by vrazdalovschi** [killbill/killbill#1324] opened 2020-07-16 18:42 UTC
Issue: PaymentControlPlugin doens't handle retry mechanism for apiPayments. Need to add custom plugin if you want to have possibility to retry your calls. 

Solution: In [PaymentConfig ](https://github.com/killbill/killbill/blob/master/util/src/main/java/org/killbill/billing/util/config/definition/PaymentConfig.java) to add new parameter, like enale.retry.apipayments with default value false, to not break flow for another users and to use this flag in computeNextRetryDate. 
https://github.com/killbill/killbill/blob/a61afae430e103feba18b65772ec225fe2266105/payment/src/main/java/org/killbill/billing/payment/invoice/InvoicePaymentControlPluginApi.java#L515

**Comment by vrazdalovschi** [comment] 2020-07-16 19:29
I found an strange behaviour, I am not sure if it should work in this way. From the CustomPaymentControlPluginApi I do simple steps. 
https://gist.github.com/vrazdalovschi/07d9ee54bde3d0b325c210f4c0f83e54

First time when come onFailure event, I add +X days according the per tenant config and later all retries are generated by system and they handled as System call, but not ApiPayment, so don't need to do manual retry again. It is a bit stranger, I would say it is a kind of bug. 
Steps: Create apiPayment. Payment should fail. CustomPaymentPluginApi will return +X days event. System retry on next time and from now default process invoice is going to handle all retries.

**Comment by sbrossie** [comment] 2020-07-17 01:03
Closing as this is not a bug: When the payment call is issued from api, the caller has the ability to retry (or schedule rtetries) if necessary, so the system does not automatically retry (this is by design).

@vrazdalovschi  Please use the public mailing list for questions and don't create issues

**Closed by sbrossie** 2020-07-17 01:03 UTC
