### ISSUE TITLE
Add support for external refunds

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#255] opened 2015-01-23 13:53 UTC
Scenario: the original credit card has been deleted and the merchant wants to issue a refund by check.

Today, this can be supported by:

* Adding an external payment method to the account and issuing a **payment credit** (to record the payment, i.e. the check)
* Adjusting the balance of the invoice by issuing an **invoice credit** (i.e. CBA)

The main drawback of this approach is that the **payment credit** won't be linked to the invoice, so the **invoice credit** won't be marked as a recognizable credit in the financial reports (i.e. real money associated to the credit vs non-recognizable credit, which is credit given to nice customers for example).

One fix would be to change `PaymentAutomatonRunner`: when retrieving the `effectivePaymentMethodId`, verify if the payment method was deleted. If it has been deleted, fail the refund. The exception can be caught at the JAX-RS level, and if the right query parameter is passed, add the external payment method if needed, and trigger the **payment credit** against that payment method. We still need to link the payment to that invoice somehow.

For testing, we need to write an integration test for the scenario above using the test payment plugin.

**Comment by matias-aguero-hs** [comment] 2016-08-17 20:13
@pierre I started working on this issue and I have some issues implementing the solution you posted in previous comment.

> if the right query parameter is passed, add the external payment method if needed, and trigger the payment credit against that payment method

Can you please check if I'm in the correct way with **[this code](https://gist.github.com/matias-aguero-hs/7ae4d42f71caad2be320f57e62c35edd#file-paymentresource-java-L510-L542)**?

I'm getting an error when the credit is created over the external payment method:
```Log
INFO  o.k.b.p.api.DefaultPaymentApi  - ENTERING PaymentApi: transactionType='PURCHASE', accountId='7ef6f244-398d-489c-ba76-fd23669fe9c2', paymentMethodId='a2bd323f-4e62-4676-b97f-2af17addaa11', paymentTransactionExternalKey='f1b64a5b-02c0-4066-af5e-1c1737d8e18a', amount='10', currency='USD' 
INFO  o.k.b.p.api.DefaultPaymentApi  - EXITING PaymentApi: transactionType='PURCHASE', accountId='7ef6f244-398d-489c-ba76-fd23669fe9c2', paymentMethodId='a2bd323f-4e62-4676-b97f-2af17addaa11', paymentExternalKey='3a3c5e19-571f-41d2-add0-c17d7fed655c', paymentTransactionExternalKey='f1b64a5b-02c0-4066-af5e-1c1737d8e18a', paymentId='3a3c5e19-571f-41d2-add0-c17d7fed655c', transactionId='25b298c9-bd41-42fa-a0cf-b9c72c0590d9', amount='10.00', currency='USD', transactionStatus='SUCCESS' 
INFO  o.k.b.p.api.DefaultPaymentApi  - ENTERING PaymentApi: transactionType='CREDIT', accountId='7ef6f244-398d-489c-ba76-fd23669fe9c2', paymentMethodId='a2bd323f-4e62-4676-b97f-2af17addaa11', paymentExternalKey='3a3c5e19-571f-41d2-add0-c17d7fed655c', paymentTransactionExternalKey='f1b64a5b-02c0-4066-af5e-1c1737d8e18a', paymentId='3a3c5e19-571f-41d2-add0-c17d7fed655c', amount='10', currency='USD' 
INFO  o.k.b.p.api.DefaultPaymentApi  - EXITING PaymentApi: transactionType='CREDIT', accountId='7ef6f244-398d-489c-ba76-fd23669fe9c2' 
WARN  o.k.b.j.m.LoggingResponse      - Bad request 
org.killbill.billing.payment.api.PaymentApiException: Invalid parameter transactionType: CREDIT doesn't match existing transaction type PURCHASE
	at org.killbill.billing.payment.core.PaymentProcessor.findTransactionToCompleteAndRunSanityChecks(PaymentProcessor.java:487)
	at org.killbill.billing.payment.core.PaymentProcessor.performOperation(PaymentProcessor.java:425)
	at org.killbill.billing.payment.core.PaymentProcessor.performOperation(PaymentProcessor.java:373)
	at org.killbill.billing.payment.core.PaymentProcessor.createCredit(PaymentProcessor.java:164)
	at org.killbill.billing.payment.api.DefaultPaymentApi.createCredit(DefaultPaymentApi.java:522)
```

**Comment by pierre** [comment] 2016-08-17 23:30
> Can you please check if I'm in the correct way with **[this code](https://gist.github.com/matias-aguero-hs/7ae4d42f71caad2be320f57e62c35edd#file-paymentresource-java-L510-L542)**?

Let me take a step back, since I realized the code changed quite a bit since my comment was written 🙊 

There are two scenarios we would like to support:

1. The account was tagged with `MANUAL_PAY`, i.e. paying invoices by checks. Payments are recorded manually (e.g. via Kaui) using [InvoiceResource#createInstantPayment](https://github.com/killbill/killbill/blob/master/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoiceResource.java#L592). The merchant now decides to trigger a refund by sending a check to the user: the refund is recorded manually via [InvoicePaymentResource#createRefundWithAdjustments](https://github.com/killbill/killbill/blob/master/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoicePaymentResource.java#L145). This may already work as-is today (`createInstantPayment` would have created the external payment method, and a refund (`REFUND` operation against a `PURCHASE`, see below) against the payment method should go through) -- to be verified.
2. The account was paying its invoices automatically via a credit card payment method. For whatever reason (e.g. account closed), that account doesn't have the credit card on file anymore (deleted payment method). In that case, we cannot trigger a refund anymore (the payment method has been deleted), so we need to trigger a `CREDIT` operation against a new payment method. It could be the external payment method (if the merchant sends a check) or a different credit card (if the customer has another credit card payment method on file).

At a high level, regarding the implementation, I would suggest to update [InvoicePaymentResource#createRefundWithAdjustments](https://github.com/killbill/killbill/blob/master/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoicePaymentResource.java#L145) and pass an extra query parameter `@QueryParam(QUERY_PAYMENT_EXTERNAL) @DefaultValue("false") final Boolean externalPayment`. If this is set to true, we are in the scenario 2a above (the merchant sends a check). The code should [understand](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/core/PaymentMethodProcessor.java#L372-L381) that the external payment method needs to be created if it doesn't exist yet and trigger a `CREDIT` using the (built-in) external payment plugin. Additionally, we could also add a second parameter `paymentMethodId`. In that case, we are in the scenario 2b above (__refund__ on a different payment method) and the code should also trigger a `CREDIT` operation (see below) on that payment method (we should prevent a `CREDIT` operation on the same payment method that was used for the original payment though - if the user decides somehow to pass it as the query parameter). This is probably the most difficult part of this bug to implement: the [InvoicePaymentControlPluginApi](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/invoice/InvoicePaymentControlPluginApi.java#L145-L147) needs to be updated to understand the `CREDIT` operation, and update the invoice balance, adjustments, etc. as if it was a refund.

Does that make sense?

In all of these cases, the delicate part is making sure the invoice balance, adjustments, etc. accurately reflect the outcome of the refund / credit. 

> I'm getting an error when the credit is created over the external payment method

The `CREDIT` operation is an [initial operation](http://docs.killbill.io/0.16/userguide_payment.html#_payment_states) - it corresponds to the opposite of the `PURCHASE` operation, i.e. moving money from the merchant to the user. To put it different, to give money to a customer, you can either refund an existing purchase or capture, or trigger a standalone credit.

**Comment by matias-aguero-hs** [comment] 2016-08-18 13:55
> Does that make sense?

Yes, it does. It will involve more work that I'd estimated 😅 

> One fix would be to change PaymentAutomatonRunner: when retrieving the effectivePaymentMethodId, verify if the payment method was deleted. If it has been deleted, fail the refund.

Should I keep this validation?

**Comment by pierre** [comment] 2016-08-18 20:20
> Yes, it does. It will involve more work that I'd estimated 😅 

It's a large task indeed (although I expect the bulk of the work is more in the testing than in the core, but we'll see...), but it's quite a useful feature (it has been requested a few times in the past already).

> Should I keep this validation?

I believe that's already taken care of: when Kill Bill will try to retrieve the payment method, it won't find it and fail the payment. To be checked! 😼

**Comment by matias-aguero-hs** [comment] 2016-08-22 14:58
I did commit an initial implementation. The only endpoint modified is `InvoicePaymentResource#createRefundWithAdjustments` as suggested.

You can find a **[test](https://github.com/matias-aguero-hs/killbill/blob/9916896b15150e1fe1cae1975a7006a0ed4718e1/beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestPaymentRefund.java#L121-L121)** for scenario 1 and a few more **[tests](https://github.com/matias-aguero-hs/killbill/blob/9916896b15150e1fe1cae1975a7006a0ed4718e1/profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestExternalRefund.java)** for scenario 2.

I need now to work on `InvoicePaymentControlPluginApi` to ensure the code understand the credit and create the correct balance, adjustments, etc.

**Comment by matias-aguero-hs** [comment] 2016-08-23 14:23
@pierre I'm a bit stuck since I do not know how to complete some actions for scenario 2a. Specially on the invoice and adjustments side.

Suppose a refund is made over a payment that its payment method was deleted. Can you please confirm that next actions are correct? (you can check it with the code I committed)

- A new external Payment Method is created, if needed.
- A new Payment is created to issue the credit.
- A new InvoicePayment is created with creditedAmount filled.
- The problem is that I do not have relation with the original payment and invoice.

Questions:
- Should a new Invoice be created with the credit amount?
- If adjustments are passed in the request, should an adjustment item be added to the original invoice?
- How I create a relation between the original payment with the new external payment created?

**Comment by pierre** [comment] 2016-08-23 15:30
> A new Payment is created to issue the credit.

To be precise, a new payment is created using the `CREDIT` operation. Upon success, the `InvoicePaymentControlPluginApi` will invoke `InvoiceInternalApi#recordRefund` which will adjust the invoice (if needed) and create the CBA (if needed).

> The problem is that I do not have relation with the original payment and invoice.

The invoice id should be present in the plugin properties (`IPCD_INVOICE_ID`), which was populated by JAX-RS. Regarding the original payment, I'm not sure you need it, do you?

> Should a new Invoice be created with the credit amount?

No, from an invoicing point of view, it should look like just like a regular refund.

> If adjustments are passed in the request, should an adjustment item be added to the original invoice?

Yes, but all of that should be already taken care of for you, if the right plugin properties are populated (`IPCD_REFUND_IDS_AMOUNTS` and `IPCD_REFUND_WITH_ADJUSTMENTS`).

See `InvoicePaymentControlPluginApi` and `DefaultInvoiceDao#createRefund`.

> How I create a relation between the original payment with the new external payment created?

I don't think you need to: an invoice is linked to multiple `InvoicePayment`, each with its unique payment id.

Let me know what isn't clear, happy to provide further explanation.

**Comment by matias-aguero-hs** [comment] 2016-08-23 18:05
> Upon success, the InvoicePaymentControlPluginApi will invoke InvoiceInternalApi#recordRefund which will adjust the invoice (if needed) and create the CBA (if needed).

`InvoiceInternalApi#recordRefund` calls `InvoiceDao#createRefund` and it's failing because it receives the new `CREDIT` paymentId instead of the original Payment (CreditCard) and does not match with [this condition](https://github.com/matias-aguero-hs/killbill/blob/master/invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java#L437-L446).

I'm calling `PaymentApi#createCreditWithPaymentControl` if its an [external refund](https://github.com/matias-aguero-hs/killbill/commit/9916896b15150e1fe1cae1975a7006a0ed4718e1#diff-99803d832fceda8d29ac1ae571d37f7c).

```Java
if (externalPayment) {
   result = paymentApi.createCreditWithPaymentControl(account, null, null, json.getAmount(), account.getCurrency(),
                                                      paymentExternalKey, transactionExternalKey, pluginProperties,
                                                      createInvoicePaymentControlPluginApiPaymentOptions(false), callContext);
} else {
   result = paymentApi.createRefundWithPaymentControl(account, payment.getId(), json.getAmount(), account.getCurrency(), transactionExternalKey,
                                                     pluginProperties, createInvoicePaymentControlPluginApiPaymentOptions(false), callContext);
}
```

**Comment by pierre** [comment] 2016-08-23 18:36
> `InvoiceInternalApi#recordRefund` calls `InvoiceDao#createRefund` and it's failing because it receives the new `CREDIT` paymentId instead of the original Payment (CreditCard) and does not match with [this condition](https://github.com/matias-aguero-hs/killbill/blob/master/invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java#L437-L446).

Oh, I see. Maybe you could change the internal API and/or the DAO API to add an extra `invoiceId` parameter (AFAICT, the `payment` is only retrieved to get access to the invoice id and the amount / currency)?

> I'm calling `PaymentApi#createCreditWithPaymentControl` if its an [external refund](https://github.com/matias-aguero-hs/killbill/commit/9916896b15150e1fe1cae1975a7006a0ed4718e1#diff-99803d832fceda8d29ac1ae571d37f7c).

Makes sense. However, for scenario 2b, should you also call it if the original payment method was deleted (i.e. if another payment method id was passed)?

**Comment by matias-aguero-hs** [comment] 2016-08-24 20:23
@pierre Thank you for your explanations.

I just pushed the refund implementation and tests for scenario 1 and 2a (with and without adjustments). I also created two PRs for you, so you can start reviewing the code.

- killbill-client-java: https://github.com/killbill/killbill-client-java/pull/47
- killbill: https://github.com/killbill/killbill/pull/606

Scenario 2b (refund on a different payment method) is still pending. It's my next task.

**Comment by matias-aguero-hs** [comment] 2016-09-21 18:01
I just pushed the pending work.

**Closed** 2016-09-29 16:51 UTC
Labels: enhancement, INVOICE, PAYMENT
