### ISSUE TITLE
Support for account with no payment methods.

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#163] opened 2014-03-04 19:44 UTC
Today deleting a default payment method on an account is not allowed unless we specified to also switch the account into AUTO_PAY_OFF. The goal was to avoid having to make payment calls on accounts that have no payment method-- code would just spit a stack trace because it does not expect to see that.

**Comment by javier-gomez-hs** [comment] 2016-06-22 15:31
@sbrossie @pierre 
Hi guys!
In the meantime until you can answer my comment in https://github.com/killbill/killbill/issues/69, I've started working on this issue.

I was able to "allow" the removal of the Default Payment Method, and now I found where is the Exception being thrown when the Payment Method Id is null during the Payment process.
My question is: should I register the Payment Attempt in the DB / Timeline? Or just return an Exception with a new Payment Failure Status (like "NO_PAYMENT_METHOD" or something like that).
The last step before applying the Payment Transaction is [this one](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/core/sm/payments/PaymentLeavingStateCallback.java#L62)

Thanks!!

Javier.

**Comment by sbrossie** [comment] 2016-06-23 20:48
@javier-gomez-hs The short story is that we want to make sure that when there is payment operation running against a given invoice, and there is no default payment method on the account, the payment gets aborted. This should happen in the [pseudo invoice plugin](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/invoice/InvoicePaymentControlPluginApi.java#L132).

**Comment by javier-gomez-hs** [comment] 2016-07-05 17:48
@sbrossie @pierre 
I've pushed some initial changes [here](https://github.com/killbill/killbill/pull/571).
Would you like to take a look?
That way the payment is being marked as "ABORTED" and the Server log is not showing any exception.

Is this the expected behavior?

Please let me know if I have to change anything else.

Thanks!

**Comment by pierre** [comment] 2016-07-05 21:01
> Would you like to take a look?

I've just posted some comments after sync'ing with @sbrossie on this feature.

> That way the payment is being marked as "ABORTED" and the Server log is not showing any exception.

Yes, it should be obvious though why the invoice wasn't paid (`log.warn` but a stacktrace would be useless though).

**Comment by javier-gomez-hs** [comment] 2016-07-06 19:20
@sbrossie @pierre 
So, before pushing my changes I've realised that there is [one integration test](https://github.com/javier-gomez-hs/killbill/blob/21d0b541d7b5687ca1bec5db2fd8defa880a437e/beatrix/src/test/java/org/killbill/billing/beatrix/integration/overdue/TestOverdueIntegration.java#L568) that is failing.

Basically, [here](https://github.com/javier-gomez-hs/killbill/blob/21d0b541d7b5687ca1bec5db2fd8defa880a437e/beatrix/src/test/java/org/killbill/billing/beatrix/integration/overdue/TestOverdueIntegration.java#L586) and [here](https://github.com/javier-gomez-hs/killbill/blob/21d0b541d7b5687ca1bec5db2fd8defa880a437e/beatrix/src/test/java/org/killbill/billing/beatrix/integration/overdue/TestOverdueIntegration.java#L601) the **OverdueListener** is waiting for a `INVOICE_PAYMENT_ERROR` event that won't come since we are not returning any payment error event when there is no Default Payment Method associated.
I've tried removing the unexpected events from both methods, but as you can see it is also waiting for the `BLOCK` events.
Question is: how should I handle these cases of the **Overdue states**?

Any thoughts?

Thanks!

**Comment by javier-gomez-hs** [comment] 2016-07-07 15:08
@sbrossie @pierre 
Apart from my [last comment](https://github.com/killbill/killbill/issues/163#issuecomment-230876539), I've created a new PR for the **killbill-api** project [here](https://github.com/killbill/killbill-api/pull/16)

Thanks!

**Comment by sbrossie** [comment] 2016-07-07 22:20
@javier-gomez-hs I would not change the behavior of the test. those events are required to indicate to the overdue system that the payment did not happen. With your change, the payment gets aborted very early so no event gets sent. We need to modify the code in `InvoicePaymentControlPluginApi` to make sure the `invoiceApi#recordPaymentAttemptCompletion` occurs and therefore [the event can be sent](https://github.com/killbill/killbill/blob/work-for-release-0.17.x/invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java#L783).

Probably the `invoiceApi#recordPaymentAttemptCompletion`  needs to happen [here](https://github.com/killbill/killbill/blob/work-for-release-0.17.x/payment/src/main/java/org/killbill/billing/payment/invoice/InvoicePaymentControlPluginApi.java#L314) before we throw. I am unclear if you can simply call  `invoiceApi#recordPaymentAttemptCompletion`  or if you have to call `invoiceApi#recordPaymentAttemptInit` prior that. Experiment with simply calling  `invoiceApi#recordPaymentAttemptCompletion`  and if this does not work, let us know why so we decide whether we need to call both or modify these internal apis.







missing invoiceApi payment

**Comment by javier-gomez-hs** [comment] 2016-07-11 19:45
@sbrossie 
I've added the fix [here](https://github.com/killbill/killbill/commit/83c21eec5ece7b1e93f7dfb222ee95673e88e891) as requested!

Please take a look and let me know if you think I should add any other change.

Thanks!

**Comment by javier-gomez-hs** [comment] 2016-07-14 14:46
@sbrossie @pierre 
I've created new Pull Requests with the changes of this issue and https://github.com/killbill/killbill/issues/69. All of them are pointing to the **work-for-release-0.17.x** branch:

- Kill Bill (Core): https://github.com/killbill/killbill/pull/576
- Kill Bill OSS Parent (0.113-SNAPSHOT): https://github.com/killbill/killbill-oss-parent/pull/6
- Kill Bill API (0.39-SNAPSHOT): https://github.com/killbill/killbill-api/pull/17
- Kill Bill Client (0.29-SNAPSHOT): https://github.com/killbill/killbill-client-java/pull/40

All Integration tests are passing. Please feel free to take a look and let me know if I have to change anything else.

Thanks!

**Closed** 2016-07-20 01:51 UTC
Labels: enhancement, PAYMENT
