### ISSUE TITLE
Investigate combo call issue 

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#622] opened 2016-09-29 16:59 UTC
A user reported an issue when using the bulk api to create subscriptions (in case of error and when specifying a `callCompletion=true` parameter. The original thread can be found [here](https://groups.google.com/forum/#!searchin/killbilling-users/nate%7Csort:relevance/killbilling-users/VDS4-CNWtpY/a6kNrG_SBQAJ)

At this point it is still a bit unclear what the issue really is -- there are steps that were provided that could be used to maybe understand better.

**Comment by javier-gomez-github** [comment] 2016-10-12 15:12
@sbrossie 
I've tried to replicate this issue, following the same steps that the user described, but maybe I'm missing something, because the response I got is a `201 Created`, even though the account doesn't have a payment method associated.
In the logs, I can see the expected message:
>
2016-10-12T14:44:36,222+0000 lvl='WARN', log='InvoicePaymentControlPluginApi', th='Plugin-th-76', xff='', rId='', aRId='1', tRId='1', Payment for invoiceId='4da1b862-34fb-41cc-b263-99171af5f18d' was not triggered, accountId='ff5025cc-1026-4992-bc20-72b76d617e48' doesn't have a default payment method
>

This is what I've added for [this ticket](https://github.com/killbill/killbill/issues/585):

Is that the expected behavior?

Thanks.

**Comment by sbrossie** [comment] 2016-10-12 22:15
@javier-gomez-github I am unclear exactly on what his issue is. Seems linked to when the call times out. I asked for clarification but so far did not get any.

**Comment by sbrossie** [comment] 2016-10-12 22:17
@javier-gomez-github At this point the main task left in original list is #219. Until we understand more about #622, i would hold off and move to #219.

**Comment by sbrossie** [comment] 2017-01-12 22:59
Additional feedback from mailing list:

I'm not sure if this is exactly the same issue, but I was able to get a similar error when trying to create a subscription on an account that had had two payment methods, and then the default one was deleted.  If I delete the non-default payment method instead, it goes through just fine.


```
2017-01-12T20:21:34,629+0000 lvl='INFO', log='LoggingFilter', th='catalina-exec-4', xff='', rId='65d1ead2-25cd-46ac-b190-05ca22be9260', aRId='', tRId='1', 149 * Server in-bound request
149 > POST http://kb:8080/1.0/kb/subscriptions?callCompletion=true&callTimeoutSec=30&requestedDate=2017-01-12T20%3A21%3A34.333Z
149 > accept: application/json
149 > content-type: application/json; charset=utf-8
149 > x-killbill-apikey: billing-v1
149 > x-killbill-apisecret: womply16
149 > x-killbill-createdby: 585334
149 > x-killbill-reason: test reason
149 > x-killbill-comment: test comment
149 > content-length: 442
149 > connection: keep-alive
149 > host: kb:8080
149 > authorization: Basic YWRtaW46cGFzc3dvcmQ=
149 > user-agent: KillBill-JavaClient/1.0
149 >

2017-01-12T20:21:34,737+0000 lvl='INFO', log='BillCycleDayCalculator', th='bus_events-th', xff='', rId='', aRId='4', tRId='1', Calculated BCD: subscriptionId='ba6cb271-0d03-47ff-ab58-c6bbe5153e2b', subscriptionStartDate='2017-02-12T20:21:34.000Z', accountTimeZone='UTC', bcd='12'
2017-01-12T20:21:34,779+0000 lvl='INFO', log='KillbillLogWriter', th='Thread-11', xff='', rId='', aRId='3', tRId='1', [org.killbill.killbill.osgi.libs.killbill.OSGIKillbillServiceReference@42ccb70f]Received event SUBSCRIPTION_CREATION for object id ba6cb271-0d03-47ff-ab58-c6bbe5153e2b of type SUBSCRIPTION for account a946d1b0-57bc-48a3-bfb1-39598754c4a1
2017-01-12T20:21:34,821+0000 lvl='INFO', log='BillCycleDayCalculator', th='bus_events-th', xff='', rId='', aRId='4', tRId='1', Calculated BCD: subscriptionId='ba6cb271-0d03-47ff-ab58-c6bbe5153e2b', subscriptionStartDate='2017-02-12T20:21:34.000Z', accountTimeZone='UTC', bcd='12'
2017-01-12T20:21:34,827+0000 lvl='INFO', log='DefaultInternalBillingApi', th='bus_events-th', xff='', rId='', aRId='4', tRId='1', Computed billing events for accountId='a946d1b0-57bc-48a3-bfb1-39598754c4a1'
Billing Events Raw
DefaultBillingEvent{type=CREATE, effectiveDate=2017-01-12T20:21:34.000Z, planPhaseName=customerfeedback-standalone-monthly-trial, subscriptionId=ba6cb271-0d03-47ff-ab58-c6bbe5153e2b, totalOrdering=13}
DefaultBillingEvent{type=PHASE, effectiveDate=2017-02-12T20:21:34.000Z, planPhaseName=customerfeedback-standalone-monthly-evergreen, subscriptionId=ba6cb271-0d03-47ff-ab58-c6bbe5153e2b, totalOrdering=14}
Billing Events After Blocking
DefaultBillingEvent{type=CREATE, effectiveDate=2017-01-12T20:21:34.000Z, planPhaseName=customerfeedback-standalone-monthly-trial, subscriptionId=ba6cb271-0d03-47ff-ab58-c6bbe5153e2b, totalOrdering=13}
DefaultBillingEvent{type=PHASE, effectiveDate=2017-02-12T20:21:34.000Z, planPhaseName=customerfeedback-standalone-monthly-evergreen, subscriptionId=ba6cb271-0d03-47ff-ab58-c6bbe5153e2b, totalOrdering=14}
2017-01-12T20:21:34,830+0000 lvl='INFO', log='FixedAndRecurringInvoiceItemGenerator', th='bus_events-th', xff='', rId='', aRId='4', tRId='1', Proposed Invoice items for invoiceId='0163096c-5c1f-48c4-bd8d-4d31ffe3602b', accountId='a946d1b0-57bc-48a3-bfb1-39598754c4a1'
DefaultBillingEvent{type=CREATE, effectiveDate=2017-01-12T20:21:34.000Z, planPhaseName=customerfeedback-standalone-monthly-trial, subscriptionId=ba6cb271-0d03-47ff-ab58-c6bbe5153e2b, totalOrdering=13}
DefaultBillingEvent{type=PHASE, effectiveDate=2017-02-12T20:21:34.000Z, planPhaseName=customerfeedback-standalone-monthly-evergreen, subscriptionId=ba6cb271-0d03-47ff-ab58-c6bbe5153e2b, totalOrdering=14}
2017-01-12T20:21:34,834+0000 lvl='INFO', log='InvoiceDispatcher', th='bus_events-th', xff='', rId='', aRId='4', tRId='1', Generated invoiceId='0163096c-5c1f-48c4-bd8d-4d31ffe3602b', numberOfItems='1', accountId='a946d1b0-57bc-48a3-bfb1-39598754c4a1', targetDate='2017-01-12':
         item = FIXED{startDate=2017-01-12, endDate=null, amount=1.00, rate=null, subscriptionId=ba6cb271-0d03-47ff-ab58-c6bbe5153e2b, linkedItemId=null}

2017-01-12T20:21:34,905+0000 lvl='INFO', log='KillbillLogWriter', th='Thread-11', xff='', rId='', aRId='3', tRId='1', [org.killbill.killbill.osgi.libs.killbill.OSGIKillbillServiceReference@3331a7f6]Received event ACCOUNT_CHANGE for object id a946d1b0-57bc-48a3-bfb1-39598754c4a1 of type ACCOUNT for account a946d1b0-57bc-48a3-bfb1-39598754c4a1
2017-01-12T20:21:35,030+0000 lvl='INFO', log='PaymentBusEventHandler', th='bus_events-th', xff='', rId='', aRId='4', tRId='1', Received invoice creation notification for accountId='a946d1b0-57bc-48a3-bfb1-39598754c4a1', invoiceId='0163096c-5c1f-48c4-bd8d-4d31ffe3602b'
2017-01-12T20:21:35,079+0000 lvl='INFO', log='SubscriptionResource', th='bus_events-th', xff='', rId='', aRId='4', tRId='1', Got event SubscriptionBaseTransition token='65d1ead2-25cd-46ac-b190-05ca22be9260', type='CREATE', remaining='0'
2017-01-12T20:21:35,080+0000 lvl='INFO', log='KillbillLogWriter', th='Thread-11', xff='', rId='', aRId='3', tRId='1', [org.killbill.killbill.osgi.libs.killbill.OSGIKillbillServiceReference@29f50c01]Received event SUBSCRIPTION_CREATION for object id ba6cb271-0d03-47ff-ab58-c6bbe5153e2b of type SUBSCRIPTION for account a946d1b0-57bc-48a3-bfb1-39598754c4a1
2017-01-12T20:21:35,150+0000 lvl='WARN', log='OperationControlCallback', th='bus_events-th', xff='', rId='', aRId='4', tRId='1', Operation failed for accountId='W_85140' accountExternalKey='Internal payment error : org.skife.jdbi.v2.exceptions.CallbackFailedException: org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: java.sql.SQLIntegrityConstraintViolationException: Column 'payment_method_id' cannot be null [statement:"insert into _invoice_payment_control_plugin_auto_pay_off (attempt_id, payment_external_key, transaction_external_key, account_id, plugin_name, payment_id, payment_method_id, amount, currency, created_by, created_date) values (?,?,?,?,?,?,?,?,?,?,?)", located:"insert into _invoice_payment_control_plugin_auto_pay_off (attempt_id, payment_external_key, transaction_external_key, account_id, plugin_name, payment_id, payment_method_id, amount, currency, created_by, created_date) values (?,?,?,?,?,?,?,?,?,?,?)", rewritten:"insert into _invoice_payment_control_plugin_auto_pay_off (attempt_id, payment_external_key, transaction_external_key, account_id, plugin_name, payment_id, payment_method_id, amount, currency, created_by, created_date) values (?,?,?,?,?,?,?,?,?,?,?)", arguments:{ positional:{0:'fc4e4dfc-a05c-460f-b8dc-850dda3b1777',1:'dce1ecf0-7b75-46b7-ba67-1038d0cf2d94',2:'c835f47b-9901-4251-8826-52fc3f386842',3:UUIDArgument{value=a946d1b0-57bc-48a3-bfb1-39598754c4a1},4:'__INVOICE_PAYMENT_CONTROL_PLUGIN__',5:null,6:null,7:1.00,8:USD,9:'InvoicePaymentControlPluginApi',10:DateTimeArgument{value=2017-01-12T20:21:35.000Z}}, named:{}, finder:[]}]' error='{}'
2017-01-12T20:21:35,205+0000 lvl='WARN', log='PaymentBusEventHandler', th='bus_events-th', xff='', rId='', aRId='4', tRId='1', Failed to process invoice payment {cause=org.skife.jdbi.v2.exceptions.CallbackFailedException: org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: java.sql.SQLIntegrityConstraintViolationException: Column 'payment_method_id' cannot be null [statement:"insert into _invoice_payment_control_plugin_auto_pay_off (attempt_id, payment_external_key, transaction_external_key, account_id, plugin_name, payment_id, payment_method_id, amount, currency, created_by, created_date) values (?,?,?,?,?,?,?,?,?,?,?)", located:"insert into _invoice_payment_control_plugin_auto_pay_off (attempt_id, payment_external_key, transaction_external_key, account_id, plugin_name, payment_id, payment_method_id, amount, currency, created_by, created_date) values (?,?,?,?,?,?,?,?,?,?,?)", rewritten:"insert into _invoice_payment_control_plugin_auto_pay_off (attempt_id, payment_external_key, transaction_external_key, account_id, plugin_name, payment_id, payment_method_id, amount, currency, created_by, created_date) values (?,?,?,?,?,?,?,?,?,?,?)", arguments:{ positional:{0:'fc4e4dfc-a05c-460f-b8dc-850dda3b1777',1:'dce1ecf0-7b75-46b7-ba67-1038d0cf2d94',2:'c835f47b-9901-4251-8826-52fc3f386842',3:UUIDArgument{value=a946d1b0-57bc-48a3-bfb1-39598754c4a1},4:'__INVOICE_PAYMENT_CONTROL_PLUGIN__',5:null,6:null,7:1.00,8:USD,9:'InvoicePaymentControlPluginApi',10:DateTimeArgument{value=2017-01-12T20:21:35.000Z}}, named:{}, finder:[]}], code=7019, formattedMsg='Internal payment error : org.skife.jdbi.v2.exceptions.CallbackFailedException: org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: java.sql.SQLIntegrityConstraintViolationException: Column 'payment_method_id' cannot be null [statement:"insert into _invoice_payment_control_plugin_auto_pay_off (attempt_id, payment_external_key, transaction_external_key, account_id, plugin_name, payment_id, payment_method_id, amount, currency, created_by, created_date) values (?,?,?,?,?,?,?,?,?,?,?)", located:"insert into _invoice_payment_control_plugin_auto_pay_off (attempt_id, payment_external_key, transaction_external_key, account_id, plugin_name, payment_id, payment_method_id, amount, currency, created_by, created_date) values (?,?,?,?,?,?,?,?,?,?,?)", rewritten:"insert into _invoice_payment_control_plugin_auto_pay_off (attempt_id, payment_external_key, transaction_external_key, account_id, plugin_name, payment_id, payment_method_id, amount, currency, created_by, created_date) values (?,?,?,?,?,?,?,?,?,?,?)", arguments:{ positional:{0:'fc4e4dfc-a05c-460f-b8dc-850dda3b1777',1:'dce1ecf0-7b75-46b7-ba67-1038d0cf2d94',2:'c835f47b-9901-4251-8826-52fc3f386842',3:UUIDArgument{value=a946d1b0-57bc-48a3-bfb1-39598754c4a1},4:'__INVOICE_PAYMENT_CONTROL_PLUGIN__',5:null,6:null,7:1.00,8:USD,9:'InvoicePaymentControlPluginApi',10:DateTimeArgument{value=2017-01-12T20:21:35.000Z}}, named:{}, finder:[]}]'}
2017-01-12T20:21:35,288+0000 lvl='INFO', log='SubscriptionResource', th='bus_events-th', xff='', rId='', aRId='4', tRId='1', Got event InvoiceCreationNotification token='65d1ead2-25cd-46ac-b190-05ca22be9260'
2017-01-12T20:21:35,290+0000 lvl='INFO', log='KillbillLogWriter', th='Thread-11', xff='', rId='', aRId='4', tRId='1', [org.killbill.killbill.osgi.libs.killbill.OSGIKillbillServiceReference@233e6665]Received event INVOICE_CREATION for object type = INVOICE, id = 0163096c-5c1f-48c4-bd8d-4d31ffe3602b
2017-01-12T20:21:35,291+0000 lvl='INFO', log='KillbillLogWriter', th='Thread-11', xff='', rId='', aRId='4', tRId='1', [org.killbill.killbill.osgi.libs.killbill.OSGIKillbillServiceReference@46dc9c2]Received event INVOICE_CREATION for object id 0163096c-5c1f-48c4-bd8d-4d31ffe3602b of type INVOICE for account a946d1b0-57bc-48a3-bfb1-39598754c4a1
2017-01-12T20:22:04,738+0000 lvl='INFO', log='LoggingFilter', th='catalina-exec-4', xff='', rId='65d1ead2-25cd-46ac-b190-05ca22be9260', aRId='4', tRId='1', 149 * Server out-bound response
149 < 408
149 < Content-Type: application/json
149 < Vary: Accept-Encoding
149 <
```

**Comment by javier-gomez-hs1** [comment] 2017-01-13 18:38
@sbrossie 
I can take a look again and try to reproduce it.
I'll let you know if I found something new.

Thanks!

**Comment by javier-gomez-hs1** [comment] 2017-01-16 19:40
@sbrossie, @pierre 
I've been trying to reproduce this issue again, and I'm always getting the expected results.
The steps I followed are:
- Create an Account with a Default Payment Method and any other Payment Method (2 in total).
- Remove the Default Payment Method (the AUTO_PAY_OFF feature is enabled by default, and can't be disabled as part of one of the issues I fixed a few months ago, available since 0.17.x)
- Create a Subscription for that Account without Trial phase (to trigger the payment).

As a result, the subscription was successfully created and in the logs I can see **the same message I posted before**:

> Payment for invoiceId='5bf442ee-0f68-4cbc-b61e-79518a887481' was not triggered, accountId='c8bc4707-e00d-4e50-ae72-5856d906c783' doesn't have a default payment method

I wonder if this issue is now fixed after our changes for version 0.17.x

Could you try to ask the same guy that reported it to confirm that it is still happening with the new version?

Thanks!

**Comment by sbrossie** [comment] 2017-01-18 22:54
@javier-gomez-github Will follow up with them

**Comment by pierre** [comment] 2018-06-16 16:16
Cannot reproduce.

**Closed by pierre** 2018-06-16 16:16 UTC
Labels: JAXRS, bug, invalid
