### ISSUE TITLE
Allow deployments as non-root resources

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#221] opened 2014-08-31 20:29 UTC
Today, Kill Bill only works when deployed as a ROOT resource.

The main culprit is the tenant filter:

https://github.com/killbill/killbill/blob/master/profiles/killbill/src/main/java/org/killbill/billing/server/security/TenantFilter.java#L130

**Comment by maguero** [comment] 2015-10-28 14:11
Assuming the server is running on http://127.0.0.1:8080/testPath/

``` Java
httpServletRequest.getRequestURI() //  ==>  http://127.0.0.1:8080/testPath/1.0/kb/tenants
// ------------
final String path = httpServletRequest.getRequestURI();  // ==> /testPath/1.0/kb/tenants
final String path = httpServletRequest.getPathInfo();   // ==> /1.0/kb/tenants
```

We can use **httpServletRequest.getPathInfo()** [here](https://github.com/maguero/killbill/blob/master/profiles/killbill/src/main/java/org/killbill/billing/server/security/TenantFilter.java#L138) to get the correct path value.

**Comment by pierre** [comment] 2015-10-28 17:34
Question: are there changes required in the [web.xml](https://github.com/killbill/killbill/blob/master/profiles/killbill/src/main/webapp/WEB-INF/web.xml) as well?

For example, if we were to run both Kill Bill (under `http://127.0.0.1:8080/killbill`) and [Kaui](https://github.com/killbill/killbill-admin-ui-standalone) (under `http://127.0.0.1:8080/kaui`), we wouldn't want the `ShiroFilter` to apply to `/kaui/*`.

**Comment by maguero** [comment] 2015-10-28 20:28
I deployed both in tomcat, but now I'm trying to see why kaui is still calling root killbill...

Log:
```
28-Oct-2015 17:22:08.315 INFO [http-nio-8080-exec-3] org.apache.catalina.core.ApplicationContext.log   Parameters: {"utf8"=>"✓", "authenticity_token"=>"pkZZ+TIMD7tY78qMlfWpUlqaxRdQnBDvjyZJEHvXp8I=", "user"=>{"kb_username"=>"admin", "password"=>"[FILTERED]"}, "commit"=>"Sign in"}

28-Oct-2015 17:22:08.337 INFO [http-nio-8080-exec-3] org.apache.catalina.core.ApplicationContext.log ===> GET http://127.0.0.1:8080/1.0/kb/security/permissions

28-Oct-2015 17:22:08.354 INFO [http-nio-8080-exec-3] org.apache.catalina.core.ApplicationContext.log <=== 404 Not Found (10.0ms)
```

catalina.properties
``` Properties
kaui.url=http://127.0.0.1:8080/killbill/
kaui.db.url=jdbc:mysql://localhost/kaui
kaui.db.username=killbill
kaui.db.password=killbill
```

Calling killbill from a REST tool is working fine. E.g: http://127.0.0.1:8080/killbill/1.0/kb/accounts

**Comment by pierre** [comment] 2015-10-28 22:30
I believe you have found a bug in the Ruby client library, good catch!

The Kaui standalone Gemfile points to the latest client [already](https://github.com/killbill/killbill-admin-ui-standalone/blob/master/Gemfile#L41), could you try to re-build it and verify [this fix](https://github.com/killbill/killbill-client-ruby/commit/4669c51b1bc6e5e12ac3e8ef7a46fc870af3f952)?

**Comment by maguero** [comment] 2015-11-02 19:41
I run a killbill instance and other App at the same time and I didn't have problems.

* killbill: http://localhost:8080/killbill/
* other: http://localhost:8080/testApp/

I called KillBill services like "getAccountByKey" from a REST tool and I got it successfully, but when I try to use the same service by Swagger I got an error because it still pointing to root path.

![killbill1](https://cloud.githubusercontent.com/assets/13876273/10891974/b9efda52-817f-11e5-8303-ed39a4810b34.png)
![killbill2](https://cloud.githubusercontent.com/assets/13876273/10891975/ba059ce8-817f-11e5-91f7-576f7af85958.png)
![killbill3](https://cloud.githubusercontent.com/assets/13876273/10892130/78ccbcec-8180-11e5-900e-2fc082eac194.png)

**Comment by pierre** [comment] 2015-11-02 23:10
Can you try to set the System Property `org.killbill.server.baseUrl`?

See also https://github.com/killbill/killbill/issues/245.

**Comment by maguero** [comment] 2015-11-03 13:40
It worked! Thanks.
Should I create the PR?

![killbill-ok](https://cloud.githubusercontent.com/assets/13876273/10909333/280f9986-8217-11e5-870d-30d297e8eb8c.png)

**Comment by pierre** [comment] 2015-11-03 14:56
> It worked! Thanks.

Awesome!

> Should I create the PR?

Sounds good! :+1:

**Comment by maguero** [comment] 2015-11-03 18:17
PR: https://github.com/killbill/killbill/pull/433

**Comment by pierre** [comment] 2015-11-03 18:45
:tada:

**Comment by sbrossie** [comment] 2016-05-13 23:56
Reopening the issue as it does not seem to be [fixed](https://groups.google.com/forum/#!topic/killbilling-users/MGGIX0Tu4p8).

It looks like there are several issues to fix:

* KB side:
  *Should understand war was not mounted as root and compute the `Location` header accordingly
  *Should not set the `host` and `path` (or maybe configurable) to allow deployment behind load balancer
* Client side:
  * Should handle cases where we return full or relative `Location` path

**Comment by javier-gomez-hs** [comment] 2016-06-08 19:44
Hi guys @pierre, @sbrossie, @maguero:
I've started working on this issue (actually, as part of https://github.com/killbill/killbill/issues/510) and I think I've found where the problem is.

Basically, in the buildLocation() method [here](https://github.com/killbill/killbill/blob/master/jaxrs/src/main/java/org/killbill/billing/jaxrs/util/JaxrsUriBuilder.java#L38), we are defining the UriBuilder object from the Resource (class and method) like this:
```
private UriBuilder getUriBuilder(final Class<? extends JaxrsResource> theClassMaybeEnhanced, @Nullable final String getMethodName) {
        final Class theClass = getNonEnhancedClass(theClassMaybeEnhanced);
        return getMethodName != null ? UriBuilder.fromResource(theClass).path(theClass, getMethodName) :
               UriBuilder.fromResource(theClass);

    }
```

That will cause that the final UriBuilder object won't contain the context path, since it is not part of the Resource / method.
Fortunately, we have that context as part of the **UriInfo** object and apparently it seems to be easily extractable.

In summary, my suggestion would be try to detect if the **UriInfo** object has a different context and in that case we need to call a customized getUriBuilder() method with the Path (and the context), Class and Method as parameters, so the **UriBuilder** object can be created like:
```
private UriBuilder getUriBuilder(final String path, final Class<? extends JaxrsResource> theClassMaybeEnhanced, @Nullable final String getMethodName) {
        final Class theClass = getNonEnhancedClass(theClassMaybeEnhanced);
        return getMethodName != null ? UriBuilder.fromPath(path).path(theClass, getMethodName) :
               UriBuilder.fromResource(theClass);
    }
```

Please, I'd like to know your thoughts about this. Of course this is a first approach and I'll continue trying to find different solutions. 

Thanks!

**Comment by sbrossie** [comment] 2016-06-08 21:49
@javier-gomez-hs That seems like a reasonable approach. I would also add that we probably want to allow to return either a full `Location` or a path-like `Location`:
* `http://127.0.0.1:8080/1.0/kb/accounts/9d74d3be-ec75-41fd-8dfc-722baae68cb1`
* `/1.0/kb/accounts/9d74d3be-ec75-41fd-8dfc-722baae68cb1`

The second form is useful for when there is a load balancer so client can compute the full URL by forming the full url using `http://LOAD_BALANCER_IP:LOAD_BALANCER_PORT/` and the `Location` returned. I would suggest to add a system property to control that behavior in the [JaxrsConfig](https://github.com/killbill/killbill/blob/9cc7df81de256de064c0254b5eb0c4b7cc2e35c9/util/src/main/java/org/killbill/billing/util/config/JaxrsConfig.java) and set the default to the first form.

**Comment by sbrossie** [comment] 2016-06-08 21:51
@javier-gomez-hs A bonus would be to fix both [java](https://github.com/killbill/killbill-client-java) and [ruby](https://github.com/killbill/killbill-client-ruby) client library to handle those two possible cases.

**Comment by javier-gomez-hs** [comment] 2016-06-09 18:36
@sbrossie Thanks for your suggestions!

I've added the new property to the JaxrsConfig, but we might have another issue and it is related to the way Javax handles the Responses when using the **created()** method. Take a look [here](http://docs.oracle.com/javaee/6/api/javax/ws/rs/core/Response.html#created%28java.net.URI%29) at the description of the parameters:

>
Parameters:
location - the URI of the new resource. If a relative URI is supplied it will be converted into an absolute URI by resolving it relative to the request URI (see UriInfo#getRequestUri).

As you can see, the URI is always being converted into an absolute URI, and that will cause some issues when trying to reply with a path-like URI. 
Apparently, there is no way to return a path-like URI as the Location Header in the Response.

I think I saw in Kill Bill some cases where the Response is a JSON object and contains the URI Location, but I'm not sure right now which Requests were.

Do you think any other way to avoid this issue?

Thanks!

**Comment by javier-gomez-hs** [comment] 2016-06-09 20:05
BTW, I have fixed the main issue of the Location without the custom path. This is working only when the new system property is set to **FALSE**. Otherwise, I have the issue described above.

**Comment by sbrossie** [comment] 2016-06-09 20:27
@javier-gomez-hs 

> I've added the new property to the JaxrsConfig, but we might have another issue and it is related to the way Javax handles the Responses when using the created() method. 

A few thoughts:
1. By looking at the jersey code for the `created()` method, it really does 2 things:
  * It sets the HTPP status to `Status.CREATED`
  * It sets the location with the value provided. Although the doc states that "If a relative URI is supplied it will be converted into an absolute URI by resolving it relative to the request URI (see UriInfo#getRequestUri).", i don't see it in the code. Did you try it?

2. We don't have to use the `created()` method from Jersey, and we could set ourself the HTPP status to `Status.CREATED` and the `Location` header if indeed there transform our provided URI value.

> BTW, I have fixed the main issue of the Location without the custom path. This is working only when the new system property is set to FALSE. Otherwise, I have the issue described above.

Great. Could you add some tests that verify that behavior --probably under [profile/killbill..jaxrs](https://github.com/killbill/killbill/tree/master/profiles/killbill/src/test/java/org/killbill/billing/jaxrs). That might require some changes in the java client as well.

**Comment by javier-gomez-hs** [comment] 2016-06-09 20:34
@sbrossie
> Although the doc states that "If a relative URI is supplied it will be converted into an absolute URI by resolving it relative to the request URI (see UriInfo#getRequestUri).", i don't see it in the code. Did you try it?

Yes, I've tried it and it is prepending the scheme, host, port and relative path before the "real" Location I'm adding to the Response.

> We don't have to use the created() method from Jersey, and we could set ourself the HTPP status to Status.CREATED and the Location header if indeed there transform our provided URI value.

That's a great approach. I could try that only when the system property is set to true. I'll let you know what happens.

> Great. Could you add some tests that verify that behavior --probably under profile/killbill..jaxrs. That might require some changes in the java client as well.

Yes, I'll add the tests. And yes, the java client might need some changes. I'll work on that and let you know when it's done.

Thanks!

**Comment by javier-gomez-hs** [comment] 2016-06-10 19:30
@sbrossie 
I was able to fix the issue with the Relative URI being converted to Absolute URI automatically.
I have verified that all the Unit Tests and Integration Tests ran successfully even when setting the new System property to "true". 
My changes are [here](https://github.com/javier-gomez-hs/killbill/commit/7a1962a91ca7b844925a0e2763fe6763ebfde6a9) if you want to take a look.
Please feel free to add any comment / change suggestion and I'll work on that asap.
In the meantime, I'll create a new integration test to verify this new behavior.

Thanks!

**Comment by pierre** [comment] 2016-06-10 21:47
> I think I saw in Kill Bill some cases where the Response is a JSON object and contains the URI Location, but I'm not sure right now which Requests were.

`POST /1.0/kb/accounts/$accountId/paymentMethods` is one of these. @sbrossie Should we get rid of these and just standardize on the Location header (probably needs to be done in 0.17.x)?

**Comment by sbrossie** [comment] 2016-06-10 22:33
@pierre Yes, we should let @maguero complete his work for `master`, and then add a cleanup task in `0.17.x`.

**Comment by javier-gomez-hs** [comment] 2016-06-13 20:22
@pierre @sbrossie 
Hi guys, I have created a Pull Request with the new changes: https://github.com/killbill/killbill/pull/559

Please, feel free to take a look at it and let me know if you think I should change anything.

Thanks!

Javier.

P.S.: For testing purposes, I had to clone the latest version of **kaui** in order to have the latest version of the **killbill-client-ruby** with [these](https://github.com/killbill/killbill-client-ruby/commit/63ab3ea76000c472767543214276f9470fd20a1d) changes. I was able to verify that the redirection worked as expected!

**Comment by sbrossie** [comment] 2016-07-20 01:50
@javier-gomez-hs Doing some cleanup in our issues. Is that completed? Can i close the issue?

**Comment by javier-gomez-hs** [comment] 2016-07-20 01:52
@sbrossie
Yes it is completed. Go ahead and close it!

Thanks!

**Closed** 2016-07-20 18:46 UTC
Labels: bug, ext-candidate, SERVER, TENANT
