### ISSUE TITLE
Intermittent HTTP payload corruption in Killbill 0.22 

### ISSUE THREAD

**Issue by sceaj** [killbill/killbill#1834] opened 2023-02-23 17:14 UTC
We are facing an issue where our custom plugins are returning 400 errors to clients even though the request is well-formed and correct.  We tried to isolate this issue to something in our plugins, but eventually we tried to reproduce the problem in a "plain vanilla" killbill environment with none of our custom code and we were able to reproduce the problem.  Every so often the HTTP payload (body) that the plugin "sees" is missing the first byte.  Because this is an intermittent problem, it is challenging to reproduce and challenging to debug.  We're able to "catch" the problem when it has happened, but we haven't been able to isolate a root cause.  In the plain vanilla case, the issue only happens about 1 in 10,000 requests, but in our test environment (we haven't released our 0.22 implementation yet) our fully configured Killbill system suffers this issue about 1 in 50 (or fewer) requests which is not acceptable.

We have created a repo that demonstrates the issue: https://github.com/sceaj/killbill-issue
Instructions are in the README.

**Comment by pierre** [comment] 2023-02-25 09:58
Thanks for the detailed report! Can you reproduce it on 0.24? 0.22 is EOL.

**Comment by reshmabidikar** [comment] 2024-05-07 02:15
Based on the comment in https://github.com/sceaj/killbill-issue?tab=readme-ov-file#killbill-issue-reproduction, looks like the issue is not reproducible in KB `0.24.x`, so closing this ticket. Please feel free to reach out via the [mailing list](https://groups.google.com/forum/#!forum/killbilling-users) if you face issues in `0.24.x`.

**Closed by reshmabidikar** 2024-05-07 02:15 UTC
