### ISSUE TITLE
get bundle api (external key) return not found after subscription canceled

### ISSUE THREAD

**Issue by tytkal** [killbill/killbill#533] opened 2016-05-02 10:33 UTC
After canceling subscription and trying to retrieve the bundle with external key it will return not found. 
It should return subscription with state cancelled.

**Comment by sbrossie** [comment] 2016-05-17 22:27
@tytkal This is the expected behavior.

* If you cancel your subscription and then retrieve it using its `id` it will show up with a `"CANCELLED` state.
* However if you  cancel your subscription and then retrieve it using its `externalKey` ti shows up as `404`. The reason is that we enforce unicity for external key for active subscriptions (but as soon as it has been cancelled this key becomes available for reuse). I don't necessarily think this is right or wrong but this is the semantics we have chosen. Note that we are using that to transfer bundle across accounts (preserving `externalKey` for the transferred bundle on the new account).

**Comment by sbrossie** [comment] 2016-05-18 18:22
@tytkal I 'd be interested to know about your use case, and whether this behavior causing some issues on your side.

**Comment by tytkal** [comment] 2016-05-23 09:36
@sbrossie I am using externalKey as a mapper between killbill subscriptionid and my system subscription id.

**Comment by sbrossie** [comment] 2016-05-23 19:22
I understand our semantics is a bit annoying. I will keep this issue open and move it to milestone 0.1.7 to see if there is something we can do.

**Comment by sbrossie** [comment] 2016-07-08 20:29
@tytkal I believe i addressed your use case by introducing a new query parameter `includedDeleted` to also returns non active bundles (matching the same `externalKey`). This will be released part of `0.17.1`

**Closed by sbrossie** 2016-07-08 20:29 UTC
Labels: bug, ENTITLEMENT
