### ISSUE TITLE
Invalid payment transition CAPTURE from state BIG_BANG_INIT

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#668] opened 2016-11-17 23:43 UTC
We have seen situations (mostly seen for Paypal) where the `last_success_state_name` from the `payments` table is NULL after a successful AUTH, and so subsequent CAPTURE fails with message 
`Invalid payment transition CAPTURE from state BIG_BANG_INIT`.

**Comment by daliwei** [comment] 2016-11-18 00:56
@sbrossie Do you know under which condition (or flow) does that case happen?

**Comment by pierre** [comment] 2016-11-18 04:54
I don't know about PayPal specifically, but we've also seen it with Adyen. Root cause seems to be in the invocation of `fixPaymentTransactionState` which specifies `lastSuccessPaymentState == null`:

* https://github.com/killbill/killbill-adyen-plugin/blob/9f014520da9542d747b76bce0d8a1f0d19cc51b0/src/main/java/org/killbill/billing/plugin/adyen/core/KillbillAdyenNotificationHandler.java#L354
* https://github.com/killbill/killbill/blob/d7a83c5c9a143ba26c9f59e1ee19bc916f10c738/payment/src/main/java/org/killbill/billing/payment/api/DefaultAdminPaymentApi.java#L46

**Comment by pierre** [comment] 2016-12-15 19:07
I believe that was fixed by https://github.com/killbill/killbill/commit/5d078fca171ad6582763d5ee64c3dacb3aac0d98.

See also discussion https://github.com/killbill/killbill-adyen-plugin/pull/60#issuecomment-263584251.

**Closed by pierre** 2016-12-15 19:07 UTC
Labels: bug, PAYMENT
