### ISSUE TITLE
Support for MySQL 8.0.3

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#1139] opened 2019-05-22 13:09 UTC
See https://jira.mariadb.org/browse/CONJ-604.

```
Caused by: java.sql.SQLException: (conn=4169) Unknown system variable 'tx_isolation'
    at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:198)
    at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:110)
    at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:235)
    at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:318)
    at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:489)
    at org.mariadb.jdbc.MariaDbConnection.getTransactionIsolation(MariaDbConnection.java:850)
    at com.zaxxer.hikari.pool.PoolUtilities.setupConnection(PoolUtilities.java:143)
    at com.zaxxer.hikari.pool.BaseHikariPool.addConnection(BaseHikariPool.java:454)
    at com.zaxxer.hikari.pool.BaseHikariPool$1.run(BaseHikariPool.java:419)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    ... 3 common frames omitted
```

**Comment by sbrossie** [comment] 2019-07-18 00:22
@pierre It looks like based on [CONJ-604](https://jira.mariadb.org/browse/CONJ-604) all we need to do is update our current version of  `mariadb-java-client` from `1.7.2` ->  `1.7.4` to correctly handle the renaming of `tx_isolation` -> `transaction_isolation`

**Comment by pierre** [comment] 2019-07-18 09:00
Yup, I think this is mostly a testing task. We should also verify we don't break integration with older versions.

**Comment by sbrossie** [comment] 2019-07-20 04:28
@pierre Updated the pom with new client -- regression seems [promising](https://circleci.com/workflow-run/113283f8-7038-49e9-80cb-1d0033c4c633)

**Comment by sbrossie** [comment] 2019-07-20 04:29
@beccagaspard Probably we will release that in our next release -- if you have to verify this solves the issue on MySQL 8.0.3, that would be great.

**Comment by sbrossie** [comment] 2019-08-01 00:22
Closed as the fix has been put in place.

**Closed by sbrossie** 2019-08-01 00:22 UTC
